
# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "website/"
  publish = "website/build"


[[redirects]]
  from = "https://fort-friend.com/api/*
  to = "http://142.93.14.162:8080/:splat"
  status = 200
  force = true
  signed ="REACT_APP_API_SECRET"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200