[Settings]
ID = REACT_APP_NETLIFY_ID_PLACEHOLDER

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "website/"
  publish = "website/build"
